/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MachinesIndexRouteImport } from './routes/machines.index'
import { Route as MachinesMachineIdRouteImport } from './routes/machines.$machineId'
import { Route as ApiProfilePhotoRouteImport } from './routes/api/profile-photo'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiDeploymentStatusRouteImport } from './routes/api/deployment-status'
import { Route as ApiTerminalPresenceRouteImport } from './routes/api/terminal/presence'
import { Route as ApiTerminalCloseRouteImport } from './routes/api/terminal/close'
import { Route as ApiAgentUpdateDotshRouteImport } from './routes/api/agent/update[.]sh'
import { Route as ApiAgentRegisterRouteImport } from './routes/api/agent/register'
import { Route as ApiAgentPollRouteImport } from './routes/api/agent/poll'
import { Route as ApiAgentInstallDotshRouteImport } from './routes/api/agent/install[.]sh'
import { Route as ApiAgentHeartbeatRouteImport } from './routes/api/agent/heartbeat'
import { Route as ApiAgentDecommissionRouteImport } from './routes/api/agent/decommission'
import { Route as ApiAgentFilesRuntimeManifestRouteImport } from './routes/api/agent/files/runtime-manifest'
import { Route as ApiAgentFilesRuntimeRouteImport } from './routes/api/agent/files/runtime'
import { Route as ApiAgentFilesRequirementsRouteImport } from './routes/api/agent/files/requirements'
import { Route as ApiAgentFilesConfigExampleJsonRouteImport } from './routes/api/agent/files/config-example-json'
import { Route as ApiAgentFilesAgentDotpyRouteImport } from './routes/api/agent/files/agent[.]py'
import { Route as ApiAgentExecutionsResultRouteImport } from './routes/api/agent/executions/result'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesIndexRoute = MachinesIndexRouteImport.update({
  id: '/machines/',
  path: '/machines/',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesMachineIdRoute = MachinesMachineIdRouteImport.update({
  id: '/machines/$machineId',
  path: '/machines/$machineId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilePhotoRoute = ApiProfilePhotoRouteImport.update({
  id: '/api/profile-photo',
  path: '/api/profile-photo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeploymentStatusRoute = ApiDeploymentStatusRouteImport.update({
  id: '/api/deployment-status',
  path: '/api/deployment-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalPresenceRoute = ApiTerminalPresenceRouteImport.update({
  id: '/api/terminal/presence',
  path: '/api/terminal/presence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalCloseRoute = ApiTerminalCloseRouteImport.update({
  id: '/api/terminal/close',
  path: '/api/terminal/close',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentUpdateDotshRoute = ApiAgentUpdateDotshRouteImport.update({
  id: '/api/agent/update.sh',
  path: '/api/agent/update.sh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRegisterRoute = ApiAgentRegisterRouteImport.update({
  id: '/api/agent/register',
  path: '/api/agent/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentPollRoute = ApiAgentPollRouteImport.update({
  id: '/api/agent/poll',
  path: '/api/agent/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentInstallDotshRoute = ApiAgentInstallDotshRouteImport.update({
  id: '/api/agent/install.sh',
  path: '/api/agent/install.sh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentHeartbeatRoute = ApiAgentHeartbeatRouteImport.update({
  id: '/api/agent/heartbeat',
  path: '/api/agent/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentDecommissionRoute = ApiAgentDecommissionRouteImport.update({
  id: '/api/agent/decommission',
  path: '/api/agent/decommission',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentFilesRuntimeManifestRoute =
  ApiAgentFilesRuntimeManifestRouteImport.update({
    id: '/api/agent/files/runtime-manifest',
    path: '/api/agent/files/runtime-manifest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentFilesRuntimeRoute = ApiAgentFilesRuntimeRouteImport.update({
  id: '/api/agent/files/runtime',
  path: '/api/agent/files/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentFilesRequirementsRoute =
  ApiAgentFilesRequirementsRouteImport.update({
    id: '/api/agent/files/requirements',
    path: '/api/agent/files/requirements',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentFilesConfigExampleJsonRoute =
  ApiAgentFilesConfigExampleJsonRouteImport.update({
    id: '/api/agent/files/config-example-json',
    path: '/api/agent/files/config-example-json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentFilesAgentDotpyRoute = ApiAgentFilesAgentDotpyRouteImport.update({
  id: '/api/agent/files/agent.py',
  path: '/api/agent/files/agent.py',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentExecutionsResultRoute =
  ApiAgentExecutionsResultRouteImport.update({
    id: '/api/agent/executions/result',
    path: '/api/agent/executions/result',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/profile': typeof ProfileRoute
  '/templates': typeof TemplatesRoute
  '/users': typeof UsersRoute
  '/api/deployment-status': typeof ApiDeploymentStatusRoute
  '/api/health': typeof ApiHealthRoute
  '/api/profile-photo': typeof ApiProfilePhotoRoute
  '/machines/$machineId': typeof MachinesMachineIdRoute
  '/machines/': typeof MachinesIndexRoute
  '/api/agent/decommission': typeof ApiAgentDecommissionRoute
  '/api/agent/heartbeat': typeof ApiAgentHeartbeatRoute
  '/api/agent/install.sh': typeof ApiAgentInstallDotshRoute
  '/api/agent/poll': typeof ApiAgentPollRoute
  '/api/agent/register': typeof ApiAgentRegisterRoute
  '/api/agent/update.sh': typeof ApiAgentUpdateDotshRoute
  '/api/terminal/close': typeof ApiTerminalCloseRoute
  '/api/terminal/presence': typeof ApiTerminalPresenceRoute
  '/api/agent/executions/result': typeof ApiAgentExecutionsResultRoute
  '/api/agent/files/agent.py': typeof ApiAgentFilesAgentDotpyRoute
  '/api/agent/files/config-example-json': typeof ApiAgentFilesConfigExampleJsonRoute
  '/api/agent/files/requirements': typeof ApiAgentFilesRequirementsRoute
  '/api/agent/files/runtime': typeof ApiAgentFilesRuntimeRoute
  '/api/agent/files/runtime-manifest': typeof ApiAgentFilesRuntimeManifestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/profile': typeof ProfileRoute
  '/templates': typeof TemplatesRoute
  '/users': typeof UsersRoute
  '/api/deployment-status': typeof ApiDeploymentStatusRoute
  '/api/health': typeof ApiHealthRoute
  '/api/profile-photo': typeof ApiProfilePhotoRoute
  '/machines/$machineId': typeof MachinesMachineIdRoute
  '/machines': typeof MachinesIndexRoute
  '/api/agent/decommission': typeof ApiAgentDecommissionRoute
  '/api/agent/heartbeat': typeof ApiAgentHeartbeatRoute
  '/api/agent/install.sh': typeof ApiAgentInstallDotshRoute
  '/api/agent/poll': typeof ApiAgentPollRoute
  '/api/agent/register': typeof ApiAgentRegisterRoute
  '/api/agent/update.sh': typeof ApiAgentUpdateDotshRoute
  '/api/terminal/close': typeof ApiTerminalCloseRoute
  '/api/terminal/presence': typeof ApiTerminalPresenceRoute
  '/api/agent/executions/result': typeof ApiAgentExecutionsResultRoute
  '/api/agent/files/agent.py': typeof ApiAgentFilesAgentDotpyRoute
  '/api/agent/files/config-example-json': typeof ApiAgentFilesConfigExampleJsonRoute
  '/api/agent/files/requirements': typeof ApiAgentFilesRequirementsRoute
  '/api/agent/files/runtime': typeof ApiAgentFilesRuntimeRoute
  '/api/agent/files/runtime-manifest': typeof ApiAgentFilesRuntimeManifestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/profile': typeof ProfileRoute
  '/templates': typeof TemplatesRoute
  '/users': typeof UsersRoute
  '/api/deployment-status': typeof ApiDeploymentStatusRoute
  '/api/health': typeof ApiHealthRoute
  '/api/profile-photo': typeof ApiProfilePhotoRoute
  '/machines/$machineId': typeof MachinesMachineIdRoute
  '/machines/': typeof MachinesIndexRoute
  '/api/agent/decommission': typeof ApiAgentDecommissionRoute
  '/api/agent/heartbeat': typeof ApiAgentHeartbeatRoute
  '/api/agent/install.sh': typeof ApiAgentInstallDotshRoute
  '/api/agent/poll': typeof ApiAgentPollRoute
  '/api/agent/register': typeof ApiAgentRegisterRoute
  '/api/agent/update.sh': typeof ApiAgentUpdateDotshRoute
  '/api/terminal/close': typeof ApiTerminalCloseRoute
  '/api/terminal/presence': typeof ApiTerminalPresenceRoute
  '/api/agent/executions/result': typeof ApiAgentExecutionsResultRoute
  '/api/agent/files/agent.py': typeof ApiAgentFilesAgentDotpyRoute
  '/api/agent/files/config-example-json': typeof ApiAgentFilesConfigExampleJsonRoute
  '/api/agent/files/requirements': typeof ApiAgentFilesRequirementsRoute
  '/api/agent/files/runtime': typeof ApiAgentFilesRuntimeRoute
  '/api/agent/files/runtime-manifest': typeof ApiAgentFilesRuntimeManifestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/groups'
    | '/login'
    | '/logs'
    | '/profile'
    | '/templates'
    | '/users'
    | '/api/deployment-status'
    | '/api/health'
    | '/api/profile-photo'
    | '/machines/$machineId'
    | '/machines/'
    | '/api/agent/decommission'
    | '/api/agent/heartbeat'
    | '/api/agent/install.sh'
    | '/api/agent/poll'
    | '/api/agent/register'
    | '/api/agent/update.sh'
    | '/api/terminal/close'
    | '/api/terminal/presence'
    | '/api/agent/executions/result'
    | '/api/agent/files/agent.py'
    | '/api/agent/files/config-example-json'
    | '/api/agent/files/requirements'
    | '/api/agent/files/runtime'
    | '/api/agent/files/runtime-manifest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/groups'
    | '/login'
    | '/logs'
    | '/profile'
    | '/templates'
    | '/users'
    | '/api/deployment-status'
    | '/api/health'
    | '/api/profile-photo'
    | '/machines/$machineId'
    | '/machines'
    | '/api/agent/decommission'
    | '/api/agent/heartbeat'
    | '/api/agent/install.sh'
    | '/api/agent/poll'
    | '/api/agent/register'
    | '/api/agent/update.sh'
    | '/api/terminal/close'
    | '/api/terminal/presence'
    | '/api/agent/executions/result'
    | '/api/agent/files/agent.py'
    | '/api/agent/files/config-example-json'
    | '/api/agent/files/requirements'
    | '/api/agent/files/runtime'
    | '/api/agent/files/runtime-manifest'
  id:
    | '__root__'
    | '/'
    | '/groups'
    | '/login'
    | '/logs'
    | '/profile'
    | '/templates'
    | '/users'
    | '/api/deployment-status'
    | '/api/health'
    | '/api/profile-photo'
    | '/machines/$machineId'
    | '/machines/'
    | '/api/agent/decommission'
    | '/api/agent/heartbeat'
    | '/api/agent/install.sh'
    | '/api/agent/poll'
    | '/api/agent/register'
    | '/api/agent/update.sh'
    | '/api/terminal/close'
    | '/api/terminal/presence'
    | '/api/agent/executions/result'
    | '/api/agent/files/agent.py'
    | '/api/agent/files/config-example-json'
    | '/api/agent/files/requirements'
    | '/api/agent/files/runtime'
    | '/api/agent/files/runtime-manifest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroupsRoute: typeof GroupsRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  ProfileRoute: typeof ProfileRoute
  TemplatesRoute: typeof TemplatesRoute
  UsersRoute: typeof UsersRoute
  ApiDeploymentStatusRoute: typeof ApiDeploymentStatusRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiProfilePhotoRoute: typeof ApiProfilePhotoRoute
  MachinesMachineIdRoute: typeof MachinesMachineIdRoute
  MachinesIndexRoute: typeof MachinesIndexRoute
  ApiAgentDecommissionRoute: typeof ApiAgentDecommissionRoute
  ApiAgentHeartbeatRoute: typeof ApiAgentHeartbeatRoute
  ApiAgentInstallDotshRoute: typeof ApiAgentInstallDotshRoute
  ApiAgentPollRoute: typeof ApiAgentPollRoute
  ApiAgentRegisterRoute: typeof ApiAgentRegisterRoute
  ApiAgentUpdateDotshRoute: typeof ApiAgentUpdateDotshRoute
  ApiTerminalCloseRoute: typeof ApiTerminalCloseRoute
  ApiTerminalPresenceRoute: typeof ApiTerminalPresenceRoute
  ApiAgentExecutionsResultRoute: typeof ApiAgentExecutionsResultRoute
  ApiAgentFilesAgentDotpyRoute: typeof ApiAgentFilesAgentDotpyRoute
  ApiAgentFilesConfigExampleJsonRoute: typeof ApiAgentFilesConfigExampleJsonRoute
  ApiAgentFilesRequirementsRoute: typeof ApiAgentFilesRequirementsRoute
  ApiAgentFilesRuntimeRoute: typeof ApiAgentFilesRuntimeRoute
  ApiAgentFilesRuntimeManifestRoute: typeof ApiAgentFilesRuntimeManifestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines/': {
      id: '/machines/'
      path: '/machines'
      fullPath: '/machines/'
      preLoaderRoute: typeof MachinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines/$machineId': {
      id: '/machines/$machineId'
      path: '/machines/$machineId'
      fullPath: '/machines/$machineId'
      preLoaderRoute: typeof MachinesMachineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile-photo': {
      id: '/api/profile-photo'
      path: '/api/profile-photo'
      fullPath: '/api/profile-photo'
      preLoaderRoute: typeof ApiProfilePhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deployment-status': {
      id: '/api/deployment-status'
      path: '/api/deployment-status'
      fullPath: '/api/deployment-status'
      preLoaderRoute: typeof ApiDeploymentStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal/presence': {
      id: '/api/terminal/presence'
      path: '/api/terminal/presence'
      fullPath: '/api/terminal/presence'
      preLoaderRoute: typeof ApiTerminalPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal/close': {
      id: '/api/terminal/close'
      path: '/api/terminal/close'
      fullPath: '/api/terminal/close'
      preLoaderRoute: typeof ApiTerminalCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/update.sh': {
      id: '/api/agent/update.sh'
      path: '/api/agent/update.sh'
      fullPath: '/api/agent/update.sh'
      preLoaderRoute: typeof ApiAgentUpdateDotshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/register': {
      id: '/api/agent/register'
      path: '/api/agent/register'
      fullPath: '/api/agent/register'
      preLoaderRoute: typeof ApiAgentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/poll': {
      id: '/api/agent/poll'
      path: '/api/agent/poll'
      fullPath: '/api/agent/poll'
      preLoaderRoute: typeof ApiAgentPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/install.sh': {
      id: '/api/agent/install.sh'
      path: '/api/agent/install.sh'
      fullPath: '/api/agent/install.sh'
      preLoaderRoute: typeof ApiAgentInstallDotshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/heartbeat': {
      id: '/api/agent/heartbeat'
      path: '/api/agent/heartbeat'
      fullPath: '/api/agent/heartbeat'
      preLoaderRoute: typeof ApiAgentHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/decommission': {
      id: '/api/agent/decommission'
      path: '/api/agent/decommission'
      fullPath: '/api/agent/decommission'
      preLoaderRoute: typeof ApiAgentDecommissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/files/runtime-manifest': {
      id: '/api/agent/files/runtime-manifest'
      path: '/api/agent/files/runtime-manifest'
      fullPath: '/api/agent/files/runtime-manifest'
      preLoaderRoute: typeof ApiAgentFilesRuntimeManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/files/runtime': {
      id: '/api/agent/files/runtime'
      path: '/api/agent/files/runtime'
      fullPath: '/api/agent/files/runtime'
      preLoaderRoute: typeof ApiAgentFilesRuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/files/requirements': {
      id: '/api/agent/files/requirements'
      path: '/api/agent/files/requirements'
      fullPath: '/api/agent/files/requirements'
      preLoaderRoute: typeof ApiAgentFilesRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/files/config-example-json': {
      id: '/api/agent/files/config-example-json'
      path: '/api/agent/files/config-example-json'
      fullPath: '/api/agent/files/config-example-json'
      preLoaderRoute: typeof ApiAgentFilesConfigExampleJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/files/agent.py': {
      id: '/api/agent/files/agent.py'
      path: '/api/agent/files/agent.py'
      fullPath: '/api/agent/files/agent.py'
      preLoaderRoute: typeof ApiAgentFilesAgentDotpyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/executions/result': {
      id: '/api/agent/executions/result'
      path: '/api/agent/executions/result'
      fullPath: '/api/agent/executions/result'
      preLoaderRoute: typeof ApiAgentExecutionsResultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroupsRoute: GroupsRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  ProfileRoute: ProfileRoute,
  TemplatesRoute: TemplatesRoute,
  UsersRoute: UsersRoute,
  ApiDeploymentStatusRoute: ApiDeploymentStatusRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiProfilePhotoRoute: ApiProfilePhotoRoute,
  MachinesMachineIdRoute: MachinesMachineIdRoute,
  MachinesIndexRoute: MachinesIndexRoute,
  ApiAgentDecommissionRoute: ApiAgentDecommissionRoute,
  ApiAgentHeartbeatRoute: ApiAgentHeartbeatRoute,
  ApiAgentInstallDotshRoute: ApiAgentInstallDotshRoute,
  ApiAgentPollRoute: ApiAgentPollRoute,
  ApiAgentRegisterRoute: ApiAgentRegisterRoute,
  ApiAgentUpdateDotshRoute: ApiAgentUpdateDotshRoute,
  ApiTerminalCloseRoute: ApiTerminalCloseRoute,
  ApiTerminalPresenceRoute: ApiTerminalPresenceRoute,
  ApiAgentExecutionsResultRoute: ApiAgentExecutionsResultRoute,
  ApiAgentFilesAgentDotpyRoute: ApiAgentFilesAgentDotpyRoute,
  ApiAgentFilesConfigExampleJsonRoute: ApiAgentFilesConfigExampleJsonRoute,
  ApiAgentFilesRequirementsRoute: ApiAgentFilesRequirementsRoute,
  ApiAgentFilesRuntimeRoute: ApiAgentFilesRuntimeRoute,
  ApiAgentFilesRuntimeManifestRoute: ApiAgentFilesRuntimeManifestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
