/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LicenseRouteImport } from './routes/license'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MachinesIndexRouteImport } from './routes/machines.index'
import { Route as MonitoringRulesRouteImport } from './routes/monitoring.rules'
import { Route as MonitoringMachinesRouteImport } from './routes/monitoring.machines'
import { Route as MonitoringEventsRouteImport } from './routes/monitoring.events'
import { Route as MonitoringAlertsRouteImport } from './routes/monitoring.alerts'
import { Route as MachinesMachineIdRouteImport } from './routes/machines.$machineId'
import { Route as ApiProfilePhotoRouteImport } from './routes/api/profile-photo'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiDeploymentStatusRouteImport } from './routes/api/deployment-status'
import { Route as MonitoringMachinesMachineIdRouteImport } from './routes/monitoring.machines.$machineId'
import { Route as MonitoringEventsEventIdRouteImport } from './routes/monitoring.events_.$eventId'
import { Route as ApiTerminalPresenceRouteImport } from './routes/api/terminal/presence'
import { Route as ApiTerminalCloseRouteImport } from './routes/api/terminal/close'
import { Route as ApiSecurityRulesRouteImport } from './routes/api/security/rules'
import { Route as ApiSecurityEventsRouteImport } from './routes/api/security/events'
import { Route as ApiSecurityDashboardRouteImport } from './routes/api/security/dashboard'
import { Route as ApiSecurityAlertsRouteImport } from './routes/api/security/alerts'
import { Route as ApiAgentUpdateDotshRouteImport } from './routes/api/agent/update[.]sh'
import { Route as ApiAgentRegisterRouteImport } from './routes/api/agent/register'
import { Route as ApiAgentPollRouteImport } from './routes/api/agent/poll'
import { Route as ApiAgentInstallDotshRouteImport } from './routes/api/agent/install[.]sh'
import { Route as ApiAgentHeartbeatRouteImport } from './routes/api/agent/heartbeat'
import { Route as ApiAgentDecommissionRouteImport } from './routes/api/agent/decommission'
import { Route as ApiSecurityRulesRuleIdRouteImport } from './routes/api/security/rules.$ruleId'
import { Route as ApiSecurityEventsOverviewRouteImport } from './routes/api/security/events.overview'
import { Route as ApiSecurityEventsExportRouteImport } from './routes/api/security/events.export'
import { Route as ApiSecurityEventsEventIdRouteImport } from './routes/api/security/events.$eventId'
import { Route as ApiSecurityAlertsAlertIdRouteImport } from './routes/api/security/alerts.$alertId'
import { Route as ApiAgentSecurityEventsRouteImport } from './routes/api/agent/security/events'
import { Route as ApiAgentFilesRuntimeManifestRouteImport } from './routes/api/agent/files/runtime-manifest'
import { Route as ApiAgentFilesRuntimeRouteImport } from './routes/api/agent/files/runtime'
import { Route as ApiAgentFilesRequirementsRouteImport } from './routes/api/agent/files/requirements'
import { Route as ApiAgentFilesConfigExampleJsonRouteImport } from './routes/api/agent/files/config-example-json'
import { Route as ApiAgentFilesAgentDotpyRouteImport } from './routes/api/agent/files/agent[.]py'
import { Route as ApiAgentExecutionsResultRouteImport } from './routes/api/agent/executions/result'
import { Route as ApiSecurityAlertsAlertIdStatusRouteImport } from './routes/api/security/alerts.$alertId.status'
import { Route as ApiSecurityAlertsAlertIdCommentsRouteImport } from './routes/api/security/alerts.$alertId.comments'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesIndexRoute = MachinesIndexRouteImport.update({
  id: '/machines/',
  path: '/machines/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRulesRoute = MonitoringRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => MonitoringRoute,
} as any)
const MonitoringMachinesRoute = MonitoringMachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => MonitoringRoute,
} as any)
const MonitoringEventsRoute = MonitoringEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => MonitoringRoute,
} as any)
const MonitoringAlertsRoute = MonitoringAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => MonitoringRoute,
} as any)
const MachinesMachineIdRoute = MachinesMachineIdRouteImport.update({
  id: '/machines/$machineId',
  path: '/machines/$machineId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilePhotoRoute = ApiProfilePhotoRouteImport.update({
  id: '/api/profile-photo',
  path: '/api/profile-photo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeploymentStatusRoute = ApiDeploymentStatusRouteImport.update({
  id: '/api/deployment-status',
  path: '/api/deployment-status',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringMachinesMachineIdRoute =
  MonitoringMachinesMachineIdRouteImport.update({
    id: '/$machineId',
    path: '/$machineId',
    getParentRoute: () => MonitoringMachinesRoute,
  } as any)
const MonitoringEventsEventIdRoute = MonitoringEventsEventIdRouteImport.update({
  id: '/events_/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => MonitoringRoute,
} as any)
const ApiTerminalPresenceRoute = ApiTerminalPresenceRouteImport.update({
  id: '/api/terminal/presence',
  path: '/api/terminal/presence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalCloseRoute = ApiTerminalCloseRouteImport.update({
  id: '/api/terminal/close',
  path: '/api/terminal/close',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSecurityRulesRoute = ApiSecurityRulesRouteImport.update({
  id: '/api/security/rules',
  path: '/api/security/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSecurityEventsRoute = ApiSecurityEventsRouteImport.update({
  id: '/api/security/events',
  path: '/api/security/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSecurityDashboardRoute = ApiSecurityDashboardRouteImport.update({
  id: '/api/security/dashboard',
  path: '/api/security/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSecurityAlertsRoute = ApiSecurityAlertsRouteImport.update({
  id: '/api/security/alerts',
  path: '/api/security/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentUpdateDotshRoute = ApiAgentUpdateDotshRouteImport.update({
  id: '/api/agent/update.sh',
  path: '/api/agent/update.sh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRegisterRoute = ApiAgentRegisterRouteImport.update({
  id: '/api/agent/register',
  path: '/api/agent/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentPollRoute = ApiAgentPollRouteImport.update({
  id: '/api/agent/poll',
  path: '/api/agent/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentInstallDotshRoute = ApiAgentInstallDotshRouteImport.update({
  id: '/api/agent/install.sh',
  path: '/api/agent/install.sh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentHeartbeatRoute = ApiAgentHeartbeatRouteImport.update({
  id: '/api/agent/heartbeat',
  path: '/api/agent/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentDecommissionRoute = ApiAgentDecommissionRouteImport.update({
  id: '/api/agent/decommission',
  path: '/api/agent/decommission',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSecurityRulesRuleIdRoute = ApiSecurityRulesRuleIdRouteImport.update({
  id: '/$ruleId',
  path: '/$ruleId',
  getParentRoute: () => ApiSecurityRulesRoute,
} as any)
const ApiSecurityEventsOverviewRoute =
  ApiSecurityEventsOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ApiSecurityEventsRoute,
  } as any)
const ApiSecurityEventsExportRoute = ApiSecurityEventsExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ApiSecurityEventsRoute,
} as any)
const ApiSecurityEventsEventIdRoute =
  ApiSecurityEventsEventIdRouteImport.update({
    id: '/$eventId',
    path: '/$eventId',
    getParentRoute: () => ApiSecurityEventsRoute,
  } as any)
const ApiSecurityAlertsAlertIdRoute =
  ApiSecurityAlertsAlertIdRouteImport.update({
    id: '/$alertId',
    path: '/$alertId',
    getParentRoute: () => ApiSecurityAlertsRoute,
  } as any)
const ApiAgentSecurityEventsRoute = ApiAgentSecurityEventsRouteImport.update({
  id: '/api/agent/security/events',
  path: '/api/agent/security/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentFilesRuntimeManifestRoute =
  ApiAgentFilesRuntimeManifestRouteImport.update({
    id: '/api/agent/files/runtime-manifest',
    path: '/api/agent/files/runtime-manifest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentFilesRuntimeRoute = ApiAgentFilesRuntimeRouteImport.update({
  id: '/api/agent/files/runtime',
  path: '/api/agent/files/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentFilesRequirementsRoute =
  ApiAgentFilesRequirementsRouteImport.update({
    id: '/api/agent/files/requirements',
    path: '/api/agent/files/requirements',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentFilesConfigExampleJsonRoute =
  ApiAgentFilesConfigExampleJsonRouteImport.update({
    id: '/api/agent/files/config-example-json',
    path: '/api/agent/files/config-example-json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentFilesAgentDotpyRoute = ApiAgentFilesAgentDotpyRouteImport.update({
  id: '/api/agent/files/agent.py',
  path: '/api/agent/files/agent.py',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentExecutionsResultRoute =
  ApiAgentExecutionsResultRouteImport.update({
    id: '/api/agent/executions/result',
    path: '/api/agent/executions/result',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSecurityAlertsAlertIdStatusRoute =
  ApiSecurityAlertsAlertIdStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => ApiSecurityAlertsAlertIdRoute,
  } as any)
const ApiSecurityAlertsAlertIdCommentsRoute =
  ApiSecurityAlertsAlertIdCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => ApiSecurityAlertsAlertIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/groups': typeof GroupsRoute
  '/license': typeof LicenseRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/monitoring': typeof MonitoringRouteWithChildren
  '/policies': typeof PoliciesRoute
  '/profile': typeof ProfileRoute
  '/templates': typeof TemplatesRoute
  '/users': typeof UsersRoute
  '/api/deployment-status': typeof ApiDeploymentStatusRoute
  '/api/health': typeof ApiHealthRoute
  '/api/profile-photo': typeof ApiProfilePhotoRoute
  '/machines/$machineId': typeof MachinesMachineIdRoute
  '/monitoring/alerts': typeof MonitoringAlertsRoute
  '/monitoring/events': typeof MonitoringEventsRoute
  '/monitoring/machines': typeof MonitoringMachinesRouteWithChildren
  '/monitoring/rules': typeof MonitoringRulesRoute
  '/machines/': typeof MachinesIndexRoute
  '/api/agent/decommission': typeof ApiAgentDecommissionRoute
  '/api/agent/heartbeat': typeof ApiAgentHeartbeatRoute
  '/api/agent/install.sh': typeof ApiAgentInstallDotshRoute
  '/api/agent/poll': typeof ApiAgentPollRoute
  '/api/agent/register': typeof ApiAgentRegisterRoute
  '/api/agent/update.sh': typeof ApiAgentUpdateDotshRoute
  '/api/security/alerts': typeof ApiSecurityAlertsRouteWithChildren
  '/api/security/dashboard': typeof ApiSecurityDashboardRoute
  '/api/security/events': typeof ApiSecurityEventsRouteWithChildren
  '/api/security/rules': typeof ApiSecurityRulesRouteWithChildren
  '/api/terminal/close': typeof ApiTerminalCloseRoute
  '/api/terminal/presence': typeof ApiTerminalPresenceRoute
  '/monitoring/events/$eventId': typeof MonitoringEventsEventIdRoute
  '/monitoring/machines/$machineId': typeof MonitoringMachinesMachineIdRoute
  '/api/agent/executions/result': typeof ApiAgentExecutionsResultRoute
  '/api/agent/files/agent.py': typeof ApiAgentFilesAgentDotpyRoute
  '/api/agent/files/config-example-json': typeof ApiAgentFilesConfigExampleJsonRoute
  '/api/agent/files/requirements': typeof ApiAgentFilesRequirementsRoute
  '/api/agent/files/runtime': typeof ApiAgentFilesRuntimeRoute
  '/api/agent/files/runtime-manifest': typeof ApiAgentFilesRuntimeManifestRoute
  '/api/agent/security/events': typeof ApiAgentSecurityEventsRoute
  '/api/security/alerts/$alertId': typeof ApiSecurityAlertsAlertIdRouteWithChildren
  '/api/security/events/$eventId': typeof ApiSecurityEventsEventIdRoute
  '/api/security/events/export': typeof ApiSecurityEventsExportRoute
  '/api/security/events/overview': typeof ApiSecurityEventsOverviewRoute
  '/api/security/rules/$ruleId': typeof ApiSecurityRulesRuleIdRoute
  '/api/security/alerts/$alertId/comments': typeof ApiSecurityAlertsAlertIdCommentsRoute
  '/api/security/alerts/$alertId/status': typeof ApiSecurityAlertsAlertIdStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/groups': typeof GroupsRoute
  '/license': typeof LicenseRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/monitoring': typeof MonitoringRouteWithChildren
  '/policies': typeof PoliciesRoute
  '/profile': typeof ProfileRoute
  '/templates': typeof TemplatesRoute
  '/users': typeof UsersRoute
  '/api/deployment-status': typeof ApiDeploymentStatusRoute
  '/api/health': typeof ApiHealthRoute
  '/api/profile-photo': typeof ApiProfilePhotoRoute
  '/machines/$machineId': typeof MachinesMachineIdRoute
  '/monitoring/alerts': typeof MonitoringAlertsRoute
  '/monitoring/events': typeof MonitoringEventsRoute
  '/monitoring/machines': typeof MonitoringMachinesRouteWithChildren
  '/monitoring/rules': typeof MonitoringRulesRoute
  '/machines': typeof MachinesIndexRoute
  '/api/agent/decommission': typeof ApiAgentDecommissionRoute
  '/api/agent/heartbeat': typeof ApiAgentHeartbeatRoute
  '/api/agent/install.sh': typeof ApiAgentInstallDotshRoute
  '/api/agent/poll': typeof ApiAgentPollRoute
  '/api/agent/register': typeof ApiAgentRegisterRoute
  '/api/agent/update.sh': typeof ApiAgentUpdateDotshRoute
  '/api/security/alerts': typeof ApiSecurityAlertsRouteWithChildren
  '/api/security/dashboard': typeof ApiSecurityDashboardRoute
  '/api/security/events': typeof ApiSecurityEventsRouteWithChildren
  '/api/security/rules': typeof ApiSecurityRulesRouteWithChildren
  '/api/terminal/close': typeof ApiTerminalCloseRoute
  '/api/terminal/presence': typeof ApiTerminalPresenceRoute
  '/monitoring/events/$eventId': typeof MonitoringEventsEventIdRoute
  '/monitoring/machines/$machineId': typeof MonitoringMachinesMachineIdRoute
  '/api/agent/executions/result': typeof ApiAgentExecutionsResultRoute
  '/api/agent/files/agent.py': typeof ApiAgentFilesAgentDotpyRoute
  '/api/agent/files/config-example-json': typeof ApiAgentFilesConfigExampleJsonRoute
  '/api/agent/files/requirements': typeof ApiAgentFilesRequirementsRoute
  '/api/agent/files/runtime': typeof ApiAgentFilesRuntimeRoute
  '/api/agent/files/runtime-manifest': typeof ApiAgentFilesRuntimeManifestRoute
  '/api/agent/security/events': typeof ApiAgentSecurityEventsRoute
  '/api/security/alerts/$alertId': typeof ApiSecurityAlertsAlertIdRouteWithChildren
  '/api/security/events/$eventId': typeof ApiSecurityEventsEventIdRoute
  '/api/security/events/export': typeof ApiSecurityEventsExportRoute
  '/api/security/events/overview': typeof ApiSecurityEventsOverviewRoute
  '/api/security/rules/$ruleId': typeof ApiSecurityRulesRuleIdRoute
  '/api/security/alerts/$alertId/comments': typeof ApiSecurityAlertsAlertIdCommentsRoute
  '/api/security/alerts/$alertId/status': typeof ApiSecurityAlertsAlertIdStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/groups': typeof GroupsRoute
  '/license': typeof LicenseRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/monitoring': typeof MonitoringRouteWithChildren
  '/policies': typeof PoliciesRoute
  '/profile': typeof ProfileRoute
  '/templates': typeof TemplatesRoute
  '/users': typeof UsersRoute
  '/api/deployment-status': typeof ApiDeploymentStatusRoute
  '/api/health': typeof ApiHealthRoute
  '/api/profile-photo': typeof ApiProfilePhotoRoute
  '/machines/$machineId': typeof MachinesMachineIdRoute
  '/monitoring/alerts': typeof MonitoringAlertsRoute
  '/monitoring/events': typeof MonitoringEventsRoute
  '/monitoring/machines': typeof MonitoringMachinesRouteWithChildren
  '/monitoring/rules': typeof MonitoringRulesRoute
  '/machines/': typeof MachinesIndexRoute
  '/api/agent/decommission': typeof ApiAgentDecommissionRoute
  '/api/agent/heartbeat': typeof ApiAgentHeartbeatRoute
  '/api/agent/install.sh': typeof ApiAgentInstallDotshRoute
  '/api/agent/poll': typeof ApiAgentPollRoute
  '/api/agent/register': typeof ApiAgentRegisterRoute
  '/api/agent/update.sh': typeof ApiAgentUpdateDotshRoute
  '/api/security/alerts': typeof ApiSecurityAlertsRouteWithChildren
  '/api/security/dashboard': typeof ApiSecurityDashboardRoute
  '/api/security/events': typeof ApiSecurityEventsRouteWithChildren
  '/api/security/rules': typeof ApiSecurityRulesRouteWithChildren
  '/api/terminal/close': typeof ApiTerminalCloseRoute
  '/api/terminal/presence': typeof ApiTerminalPresenceRoute
  '/monitoring/events_/$eventId': typeof MonitoringEventsEventIdRoute
  '/monitoring/machines/$machineId': typeof MonitoringMachinesMachineIdRoute
  '/api/agent/executions/result': typeof ApiAgentExecutionsResultRoute
  '/api/agent/files/agent.py': typeof ApiAgentFilesAgentDotpyRoute
  '/api/agent/files/config-example-json': typeof ApiAgentFilesConfigExampleJsonRoute
  '/api/agent/files/requirements': typeof ApiAgentFilesRequirementsRoute
  '/api/agent/files/runtime': typeof ApiAgentFilesRuntimeRoute
  '/api/agent/files/runtime-manifest': typeof ApiAgentFilesRuntimeManifestRoute
  '/api/agent/security/events': typeof ApiAgentSecurityEventsRoute
  '/api/security/alerts/$alertId': typeof ApiSecurityAlertsAlertIdRouteWithChildren
  '/api/security/events/$eventId': typeof ApiSecurityEventsEventIdRoute
  '/api/security/events/export': typeof ApiSecurityEventsExportRoute
  '/api/security/events/overview': typeof ApiSecurityEventsOverviewRoute
  '/api/security/rules/$ruleId': typeof ApiSecurityRulesRuleIdRoute
  '/api/security/alerts/$alertId/comments': typeof ApiSecurityAlertsAlertIdCommentsRoute
  '/api/security/alerts/$alertId/status': typeof ApiSecurityAlertsAlertIdStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/groups'
    | '/license'
    | '/login'
    | '/logs'
    | '/monitoring'
    | '/policies'
    | '/profile'
    | '/templates'
    | '/users'
    | '/api/deployment-status'
    | '/api/health'
    | '/api/profile-photo'
    | '/machines/$machineId'
    | '/monitoring/alerts'
    | '/monitoring/events'
    | '/monitoring/machines'
    | '/monitoring/rules'
    | '/machines/'
    | '/api/agent/decommission'
    | '/api/agent/heartbeat'
    | '/api/agent/install.sh'
    | '/api/agent/poll'
    | '/api/agent/register'
    | '/api/agent/update.sh'
    | '/api/security/alerts'
    | '/api/security/dashboard'
    | '/api/security/events'
    | '/api/security/rules'
    | '/api/terminal/close'
    | '/api/terminal/presence'
    | '/monitoring/events/$eventId'
    | '/monitoring/machines/$machineId'
    | '/api/agent/executions/result'
    | '/api/agent/files/agent.py'
    | '/api/agent/files/config-example-json'
    | '/api/agent/files/requirements'
    | '/api/agent/files/runtime'
    | '/api/agent/files/runtime-manifest'
    | '/api/agent/security/events'
    | '/api/security/alerts/$alertId'
    | '/api/security/events/$eventId'
    | '/api/security/events/export'
    | '/api/security/events/overview'
    | '/api/security/rules/$ruleId'
    | '/api/security/alerts/$alertId/comments'
    | '/api/security/alerts/$alertId/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/groups'
    | '/license'
    | '/login'
    | '/logs'
    | '/monitoring'
    | '/policies'
    | '/profile'
    | '/templates'
    | '/users'
    | '/api/deployment-status'
    | '/api/health'
    | '/api/profile-photo'
    | '/machines/$machineId'
    | '/monitoring/alerts'
    | '/monitoring/events'
    | '/monitoring/machines'
    | '/monitoring/rules'
    | '/machines'
    | '/api/agent/decommission'
    | '/api/agent/heartbeat'
    | '/api/agent/install.sh'
    | '/api/agent/poll'
    | '/api/agent/register'
    | '/api/agent/update.sh'
    | '/api/security/alerts'
    | '/api/security/dashboard'
    | '/api/security/events'
    | '/api/security/rules'
    | '/api/terminal/close'
    | '/api/terminal/presence'
    | '/monitoring/events/$eventId'
    | '/monitoring/machines/$machineId'
    | '/api/agent/executions/result'
    | '/api/agent/files/agent.py'
    | '/api/agent/files/config-example-json'
    | '/api/agent/files/requirements'
    | '/api/agent/files/runtime'
    | '/api/agent/files/runtime-manifest'
    | '/api/agent/security/events'
    | '/api/security/alerts/$alertId'
    | '/api/security/events/$eventId'
    | '/api/security/events/export'
    | '/api/security/events/overview'
    | '/api/security/rules/$ruleId'
    | '/api/security/alerts/$alertId/comments'
    | '/api/security/alerts/$alertId/status'
  id:
    | '__root__'
    | '/'
    | '/groups'
    | '/license'
    | '/login'
    | '/logs'
    | '/monitoring'
    | '/policies'
    | '/profile'
    | '/templates'
    | '/users'
    | '/api/deployment-status'
    | '/api/health'
    | '/api/profile-photo'
    | '/machines/$machineId'
    | '/monitoring/alerts'
    | '/monitoring/events'
    | '/monitoring/machines'
    | '/monitoring/rules'
    | '/machines/'
    | '/api/agent/decommission'
    | '/api/agent/heartbeat'
    | '/api/agent/install.sh'
    | '/api/agent/poll'
    | '/api/agent/register'
    | '/api/agent/update.sh'
    | '/api/security/alerts'
    | '/api/security/dashboard'
    | '/api/security/events'
    | '/api/security/rules'
    | '/api/terminal/close'
    | '/api/terminal/presence'
    | '/monitoring/events_/$eventId'
    | '/monitoring/machines/$machineId'
    | '/api/agent/executions/result'
    | '/api/agent/files/agent.py'
    | '/api/agent/files/config-example-json'
    | '/api/agent/files/requirements'
    | '/api/agent/files/runtime'
    | '/api/agent/files/runtime-manifest'
    | '/api/agent/security/events'
    | '/api/security/alerts/$alertId'
    | '/api/security/events/$eventId'
    | '/api/security/events/export'
    | '/api/security/events/overview'
    | '/api/security/rules/$ruleId'
    | '/api/security/alerts/$alertId/comments'
    | '/api/security/alerts/$alertId/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroupsRoute: typeof GroupsRoute
  LicenseRoute: typeof LicenseRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  MonitoringRoute: typeof MonitoringRouteWithChildren
  PoliciesRoute: typeof PoliciesRoute
  ProfileRoute: typeof ProfileRoute
  TemplatesRoute: typeof TemplatesRoute
  UsersRoute: typeof UsersRoute
  ApiDeploymentStatusRoute: typeof ApiDeploymentStatusRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiProfilePhotoRoute: typeof ApiProfilePhotoRoute
  MachinesMachineIdRoute: typeof MachinesMachineIdRoute
  MachinesIndexRoute: typeof MachinesIndexRoute
  ApiAgentDecommissionRoute: typeof ApiAgentDecommissionRoute
  ApiAgentHeartbeatRoute: typeof ApiAgentHeartbeatRoute
  ApiAgentInstallDotshRoute: typeof ApiAgentInstallDotshRoute
  ApiAgentPollRoute: typeof ApiAgentPollRoute
  ApiAgentRegisterRoute: typeof ApiAgentRegisterRoute
  ApiAgentUpdateDotshRoute: typeof ApiAgentUpdateDotshRoute
  ApiSecurityAlertsRoute: typeof ApiSecurityAlertsRouteWithChildren
  ApiSecurityDashboardRoute: typeof ApiSecurityDashboardRoute
  ApiSecurityEventsRoute: typeof ApiSecurityEventsRouteWithChildren
  ApiSecurityRulesRoute: typeof ApiSecurityRulesRouteWithChildren
  ApiTerminalCloseRoute: typeof ApiTerminalCloseRoute
  ApiTerminalPresenceRoute: typeof ApiTerminalPresenceRoute
  ApiAgentExecutionsResultRoute: typeof ApiAgentExecutionsResultRoute
  ApiAgentFilesAgentDotpyRoute: typeof ApiAgentFilesAgentDotpyRoute
  ApiAgentFilesConfigExampleJsonRoute: typeof ApiAgentFilesConfigExampleJsonRoute
  ApiAgentFilesRequirementsRoute: typeof ApiAgentFilesRequirementsRoute
  ApiAgentFilesRuntimeRoute: typeof ApiAgentFilesRuntimeRoute
  ApiAgentFilesRuntimeManifestRoute: typeof ApiAgentFilesRuntimeManifestRoute
  ApiAgentSecurityEventsRoute: typeof ApiAgentSecurityEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines/': {
      id: '/machines/'
      path: '/machines'
      fullPath: '/machines/'
      preLoaderRoute: typeof MachinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring/rules': {
      id: '/monitoring/rules'
      path: '/rules'
      fullPath: '/monitoring/rules'
      preLoaderRoute: typeof MonitoringRulesRouteImport
      parentRoute: typeof MonitoringRoute
    }
    '/monitoring/machines': {
      id: '/monitoring/machines'
      path: '/machines'
      fullPath: '/monitoring/machines'
      preLoaderRoute: typeof MonitoringMachinesRouteImport
      parentRoute: typeof MonitoringRoute
    }
    '/monitoring/events': {
      id: '/monitoring/events'
      path: '/events'
      fullPath: '/monitoring/events'
      preLoaderRoute: typeof MonitoringEventsRouteImport
      parentRoute: typeof MonitoringRoute
    }
    '/monitoring/alerts': {
      id: '/monitoring/alerts'
      path: '/alerts'
      fullPath: '/monitoring/alerts'
      preLoaderRoute: typeof MonitoringAlertsRouteImport
      parentRoute: typeof MonitoringRoute
    }
    '/machines/$machineId': {
      id: '/machines/$machineId'
      path: '/machines/$machineId'
      fullPath: '/machines/$machineId'
      preLoaderRoute: typeof MachinesMachineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile-photo': {
      id: '/api/profile-photo'
      path: '/api/profile-photo'
      fullPath: '/api/profile-photo'
      preLoaderRoute: typeof ApiProfilePhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deployment-status': {
      id: '/api/deployment-status'
      path: '/api/deployment-status'
      fullPath: '/api/deployment-status'
      preLoaderRoute: typeof ApiDeploymentStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring/machines/$machineId': {
      id: '/monitoring/machines/$machineId'
      path: '/$machineId'
      fullPath: '/monitoring/machines/$machineId'
      preLoaderRoute: typeof MonitoringMachinesMachineIdRouteImport
      parentRoute: typeof MonitoringMachinesRoute
    }
    '/monitoring/events_/$eventId': {
      id: '/monitoring/events_/$eventId'
      path: '/events/$eventId'
      fullPath: '/monitoring/events/$eventId'
      preLoaderRoute: typeof MonitoringEventsEventIdRouteImport
      parentRoute: typeof MonitoringRoute
    }
    '/api/terminal/presence': {
      id: '/api/terminal/presence'
      path: '/api/terminal/presence'
      fullPath: '/api/terminal/presence'
      preLoaderRoute: typeof ApiTerminalPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal/close': {
      id: '/api/terminal/close'
      path: '/api/terminal/close'
      fullPath: '/api/terminal/close'
      preLoaderRoute: typeof ApiTerminalCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/security/rules': {
      id: '/api/security/rules'
      path: '/api/security/rules'
      fullPath: '/api/security/rules'
      preLoaderRoute: typeof ApiSecurityRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/security/events': {
      id: '/api/security/events'
      path: '/api/security/events'
      fullPath: '/api/security/events'
      preLoaderRoute: typeof ApiSecurityEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/security/dashboard': {
      id: '/api/security/dashboard'
      path: '/api/security/dashboard'
      fullPath: '/api/security/dashboard'
      preLoaderRoute: typeof ApiSecurityDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/security/alerts': {
      id: '/api/security/alerts'
      path: '/api/security/alerts'
      fullPath: '/api/security/alerts'
      preLoaderRoute: typeof ApiSecurityAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/update.sh': {
      id: '/api/agent/update.sh'
      path: '/api/agent/update.sh'
      fullPath: '/api/agent/update.sh'
      preLoaderRoute: typeof ApiAgentUpdateDotshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/register': {
      id: '/api/agent/register'
      path: '/api/agent/register'
      fullPath: '/api/agent/register'
      preLoaderRoute: typeof ApiAgentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/poll': {
      id: '/api/agent/poll'
      path: '/api/agent/poll'
      fullPath: '/api/agent/poll'
      preLoaderRoute: typeof ApiAgentPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/install.sh': {
      id: '/api/agent/install.sh'
      path: '/api/agent/install.sh'
      fullPath: '/api/agent/install.sh'
      preLoaderRoute: typeof ApiAgentInstallDotshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/heartbeat': {
      id: '/api/agent/heartbeat'
      path: '/api/agent/heartbeat'
      fullPath: '/api/agent/heartbeat'
      preLoaderRoute: typeof ApiAgentHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/decommission': {
      id: '/api/agent/decommission'
      path: '/api/agent/decommission'
      fullPath: '/api/agent/decommission'
      preLoaderRoute: typeof ApiAgentDecommissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/security/rules/$ruleId': {
      id: '/api/security/rules/$ruleId'
      path: '/$ruleId'
      fullPath: '/api/security/rules/$ruleId'
      preLoaderRoute: typeof ApiSecurityRulesRuleIdRouteImport
      parentRoute: typeof ApiSecurityRulesRoute
    }
    '/api/security/events/overview': {
      id: '/api/security/events/overview'
      path: '/overview'
      fullPath: '/api/security/events/overview'
      preLoaderRoute: typeof ApiSecurityEventsOverviewRouteImport
      parentRoute: typeof ApiSecurityEventsRoute
    }
    '/api/security/events/export': {
      id: '/api/security/events/export'
      path: '/export'
      fullPath: '/api/security/events/export'
      preLoaderRoute: typeof ApiSecurityEventsExportRouteImport
      parentRoute: typeof ApiSecurityEventsRoute
    }
    '/api/security/events/$eventId': {
      id: '/api/security/events/$eventId'
      path: '/$eventId'
      fullPath: '/api/security/events/$eventId'
      preLoaderRoute: typeof ApiSecurityEventsEventIdRouteImport
      parentRoute: typeof ApiSecurityEventsRoute
    }
    '/api/security/alerts/$alertId': {
      id: '/api/security/alerts/$alertId'
      path: '/$alertId'
      fullPath: '/api/security/alerts/$alertId'
      preLoaderRoute: typeof ApiSecurityAlertsAlertIdRouteImport
      parentRoute: typeof ApiSecurityAlertsRoute
    }
    '/api/agent/security/events': {
      id: '/api/agent/security/events'
      path: '/api/agent/security/events'
      fullPath: '/api/agent/security/events'
      preLoaderRoute: typeof ApiAgentSecurityEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/files/runtime-manifest': {
      id: '/api/agent/files/runtime-manifest'
      path: '/api/agent/files/runtime-manifest'
      fullPath: '/api/agent/files/runtime-manifest'
      preLoaderRoute: typeof ApiAgentFilesRuntimeManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/files/runtime': {
      id: '/api/agent/files/runtime'
      path: '/api/agent/files/runtime'
      fullPath: '/api/agent/files/runtime'
      preLoaderRoute: typeof ApiAgentFilesRuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/files/requirements': {
      id: '/api/agent/files/requirements'
      path: '/api/agent/files/requirements'
      fullPath: '/api/agent/files/requirements'
      preLoaderRoute: typeof ApiAgentFilesRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/files/config-example-json': {
      id: '/api/agent/files/config-example-json'
      path: '/api/agent/files/config-example-json'
      fullPath: '/api/agent/files/config-example-json'
      preLoaderRoute: typeof ApiAgentFilesConfigExampleJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/files/agent.py': {
      id: '/api/agent/files/agent.py'
      path: '/api/agent/files/agent.py'
      fullPath: '/api/agent/files/agent.py'
      preLoaderRoute: typeof ApiAgentFilesAgentDotpyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/executions/result': {
      id: '/api/agent/executions/result'
      path: '/api/agent/executions/result'
      fullPath: '/api/agent/executions/result'
      preLoaderRoute: typeof ApiAgentExecutionsResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/security/alerts/$alertId/status': {
      id: '/api/security/alerts/$alertId/status'
      path: '/status'
      fullPath: '/api/security/alerts/$alertId/status'
      preLoaderRoute: typeof ApiSecurityAlertsAlertIdStatusRouteImport
      parentRoute: typeof ApiSecurityAlertsAlertIdRoute
    }
    '/api/security/alerts/$alertId/comments': {
      id: '/api/security/alerts/$alertId/comments'
      path: '/comments'
      fullPath: '/api/security/alerts/$alertId/comments'
      preLoaderRoute: typeof ApiSecurityAlertsAlertIdCommentsRouteImport
      parentRoute: typeof ApiSecurityAlertsAlertIdRoute
    }
  }
}

interface MonitoringMachinesRouteChildren {
  MonitoringMachinesMachineIdRoute: typeof MonitoringMachinesMachineIdRoute
}

const MonitoringMachinesRouteChildren: MonitoringMachinesRouteChildren = {
  MonitoringMachinesMachineIdRoute: MonitoringMachinesMachineIdRoute,
}

const MonitoringMachinesRouteWithChildren =
  MonitoringMachinesRoute._addFileChildren(MonitoringMachinesRouteChildren)

interface MonitoringRouteChildren {
  MonitoringAlertsRoute: typeof MonitoringAlertsRoute
  MonitoringEventsRoute: typeof MonitoringEventsRoute
  MonitoringMachinesRoute: typeof MonitoringMachinesRouteWithChildren
  MonitoringRulesRoute: typeof MonitoringRulesRoute
  MonitoringEventsEventIdRoute: typeof MonitoringEventsEventIdRoute
}

const MonitoringRouteChildren: MonitoringRouteChildren = {
  MonitoringAlertsRoute: MonitoringAlertsRoute,
  MonitoringEventsRoute: MonitoringEventsRoute,
  MonitoringMachinesRoute: MonitoringMachinesRouteWithChildren,
  MonitoringRulesRoute: MonitoringRulesRoute,
  MonitoringEventsEventIdRoute: MonitoringEventsEventIdRoute,
}

const MonitoringRouteWithChildren = MonitoringRoute._addFileChildren(
  MonitoringRouteChildren,
)

interface ApiSecurityAlertsAlertIdRouteChildren {
  ApiSecurityAlertsAlertIdCommentsRoute: typeof ApiSecurityAlertsAlertIdCommentsRoute
  ApiSecurityAlertsAlertIdStatusRoute: typeof ApiSecurityAlertsAlertIdStatusRoute
}

const ApiSecurityAlertsAlertIdRouteChildren: ApiSecurityAlertsAlertIdRouteChildren =
  {
    ApiSecurityAlertsAlertIdCommentsRoute:
      ApiSecurityAlertsAlertIdCommentsRoute,
    ApiSecurityAlertsAlertIdStatusRoute: ApiSecurityAlertsAlertIdStatusRoute,
  }

const ApiSecurityAlertsAlertIdRouteWithChildren =
  ApiSecurityAlertsAlertIdRoute._addFileChildren(
    ApiSecurityAlertsAlertIdRouteChildren,
  )

interface ApiSecurityAlertsRouteChildren {
  ApiSecurityAlertsAlertIdRoute: typeof ApiSecurityAlertsAlertIdRouteWithChildren
}

const ApiSecurityAlertsRouteChildren: ApiSecurityAlertsRouteChildren = {
  ApiSecurityAlertsAlertIdRoute: ApiSecurityAlertsAlertIdRouteWithChildren,
}

const ApiSecurityAlertsRouteWithChildren =
  ApiSecurityAlertsRoute._addFileChildren(ApiSecurityAlertsRouteChildren)

interface ApiSecurityEventsRouteChildren {
  ApiSecurityEventsEventIdRoute: typeof ApiSecurityEventsEventIdRoute
  ApiSecurityEventsExportRoute: typeof ApiSecurityEventsExportRoute
  ApiSecurityEventsOverviewRoute: typeof ApiSecurityEventsOverviewRoute
}

const ApiSecurityEventsRouteChildren: ApiSecurityEventsRouteChildren = {
  ApiSecurityEventsEventIdRoute: ApiSecurityEventsEventIdRoute,
  ApiSecurityEventsExportRoute: ApiSecurityEventsExportRoute,
  ApiSecurityEventsOverviewRoute: ApiSecurityEventsOverviewRoute,
}

const ApiSecurityEventsRouteWithChildren =
  ApiSecurityEventsRoute._addFileChildren(ApiSecurityEventsRouteChildren)

interface ApiSecurityRulesRouteChildren {
  ApiSecurityRulesRuleIdRoute: typeof ApiSecurityRulesRuleIdRoute
}

const ApiSecurityRulesRouteChildren: ApiSecurityRulesRouteChildren = {
  ApiSecurityRulesRuleIdRoute: ApiSecurityRulesRuleIdRoute,
}

const ApiSecurityRulesRouteWithChildren =
  ApiSecurityRulesRoute._addFileChildren(ApiSecurityRulesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroupsRoute: GroupsRoute,
  LicenseRoute: LicenseRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  MonitoringRoute: MonitoringRouteWithChildren,
  PoliciesRoute: PoliciesRoute,
  ProfileRoute: ProfileRoute,
  TemplatesRoute: TemplatesRoute,
  UsersRoute: UsersRoute,
  ApiDeploymentStatusRoute: ApiDeploymentStatusRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiProfilePhotoRoute: ApiProfilePhotoRoute,
  MachinesMachineIdRoute: MachinesMachineIdRoute,
  MachinesIndexRoute: MachinesIndexRoute,
  ApiAgentDecommissionRoute: ApiAgentDecommissionRoute,
  ApiAgentHeartbeatRoute: ApiAgentHeartbeatRoute,
  ApiAgentInstallDotshRoute: ApiAgentInstallDotshRoute,
  ApiAgentPollRoute: ApiAgentPollRoute,
  ApiAgentRegisterRoute: ApiAgentRegisterRoute,
  ApiAgentUpdateDotshRoute: ApiAgentUpdateDotshRoute,
  ApiSecurityAlertsRoute: ApiSecurityAlertsRouteWithChildren,
  ApiSecurityDashboardRoute: ApiSecurityDashboardRoute,
  ApiSecurityEventsRoute: ApiSecurityEventsRouteWithChildren,
  ApiSecurityRulesRoute: ApiSecurityRulesRouteWithChildren,
  ApiTerminalCloseRoute: ApiTerminalCloseRoute,
  ApiTerminalPresenceRoute: ApiTerminalPresenceRoute,
  ApiAgentExecutionsResultRoute: ApiAgentExecutionsResultRoute,
  ApiAgentFilesAgentDotpyRoute: ApiAgentFilesAgentDotpyRoute,
  ApiAgentFilesConfigExampleJsonRoute: ApiAgentFilesConfigExampleJsonRoute,
  ApiAgentFilesRequirementsRoute: ApiAgentFilesRequirementsRoute,
  ApiAgentFilesRuntimeRoute: ApiAgentFilesRuntimeRoute,
  ApiAgentFilesRuntimeManifestRoute: ApiAgentFilesRuntimeManifestRoute,
  ApiAgentSecurityEventsRoute: ApiAgentSecurityEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
